## Load library

```{r}
library(readr)
library(dplyr)
library(ggplot2)
library(survival)
library(survminer)

```

## Load dataset
```{r}
clinical_data <- read_tsv("msk_chord_2024_clinical_data (2).tsv")


```

## Data Cleaning And Pre-Processing

## Detect Missing Value
```{r}
colSums(is.na(clinical_data))
```


## Remove Rows with Critical Missing Values

```{r}
clinical_data_clean <- clinical_data %>%
  filter(
    !is.na(`Current Age`),
    !is.na(Sex),
    !is.na(`Cancer Type`),
    !is.na(`Stage (Highest Recorded)`),
    !is.na(`Overall Survival Status`)
  )
```


## Clean NLP-Derived fields

```{r}
clinical_data_clean <- clinical_data_clean %>%
  mutate(
    `Cancer Type` = trimws(tolower(`Cancer Type`)),
    `Stage (Highest Recorded)`= trimws(toupper(`Stage (Highest Recorded)`))
  )
```


## Create Treatment Response

```{r}
clinical_data_clean <- clinical_data_clean %>%
  mutate(
    survival_status_clean = tolower(trimws(`Overall Survival Status`)),
    treatment_response = ifelse(
      grepl("alive|living", survival_status_clean),
      "Good Response",
      "Poor Response"
    )
  )


```

## Data Manipulation
## Accessing Columns

```{r}
clinical_data_clean$`Current Age`
clinical_data_clean$treatment_response

```

## Subsetting

```{r}
subset(clinical_data_clean, Sex == "Female")
```


